=== opengreat-zhoukaihong/Hutchison/cbtb/xml/organisation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by peter (peter) -->
<!ELEMENT organisation (organisation_id, organisation_type, organisation_name, organisation_chinese_name?, organisation_address, telephone, mobile_no?, fax_no?, email?, web_site?, business_registration_no, contact_person, contact_person_chinese?, billing_sent_person?, billing_email?, billing_address, billing_fax_no?, billing_telephone?, perfer_channel, perfer_language, credit_amount?, payment_terms, reason_id?, status, message?, remark?, registration_reference_no?, registration_date, registration_channel, document*)>
<!ELEMENT organisation_id (#PCDATA)>
<!ELEMENT organisation_type (#PCDATA)>
<!ELEMENT organisation_name (#PCDATA)>
<!ELEMENT organisation_chinese_name (#PCDATA)>
<!ELEMENT organisation_address (address1, address2?, address3?, address4?)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mobile_no (#PCDATA)>
<!ELEMENT fax_no (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web_site (#PCDATA)>
<!ELEMENT business_registration_no (#PCDATA)>
<!ELEMENT contact_person (#PCDATA)>
<!ELEMENT contact_person_chinese (#PCDATA)>
<!ELEMENT billing_sent_person (#PCDATA)>
<!ELEMENT billing_email (#PCDATA)>
<!ELEMENT billing_address (address1, address2?, address3?, address4?)>
<!ELEMENT billing_fax_no (#PCDATA)>
<!ELEMENT billing_telephone (#PCDATA)>
<!ELEMENT perfer_channel (#PCDATA)>
<!ELEMENT perfer_language (#PCDATA)>
<!ELEMENT credit_amount (#PCDATA)>
<!ELEMENT payment_terms (#PCDATA)>
<!ELEMENT reason_id (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT remark (#PCDATA)>
<!ELEMENT registration_reference_no (#PCDATA)>
<!ELEMENT registration_date (#PCDATA)>
<!ELEMENT registration_channel (#PCDATA)>
<!ELEMENT address1 (#PCDATA)>
<!ELEMENT address2 (#PCDATA)>
<!ELEMENT address3 (#PCDATA)>
<!ELEMENT address4 (#PCDATA)>
<!ELEMENT document (document_id, document_status)>
<!ELEMENT document_status (#PCDATA)>
<!ELEMENT document_id (#PCDATA)>

=== opengreat-zhoukaihong/Hutchison/cbtb/mq_xml/sample.xml
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by peter (peter) --><!DOCTYPE organisation SYSTEM "http://localhost:7001/organisation.dtd"><organisation><organisation_id>CB123456</organisation_id><organisation_type>shipper</organisation_type><organisation_name>Shipping Company ABC</organisation_name><organisation_address><address1>Rm1206, 12-F</address1><address2>Fortress Tower</address2><address3>North Point</address3><address4>H.K.</address4></organisation_address><telephone>(852)12345678</telephone><mobile_no>61001234</mobile_no><fax_no>(852)12344556</fax_no><email>abc@hotmail.com</email><web_site>www.shipper.com</web_site><business_registration_no>HK123456</business_registration_no><contact_person>Chan Tai Man</contact_person><billing_address><address1>Rm1206, 12-F</address1><address2>Fortress Tower</address2><address3>North Point</address3></billing_address><perfer_channel>Phone</perfer_channel><perfer_language>Chinese</perfer_language><payment_terms>COD</payment_terms><status>Registration in Progress</status><registration_date>16/05/2001</registration_date><registration_channel>web</registration_channel><UOM>KG, M</UOM><document><document_id>sh00001</document_id><document_status>valid</document_status></document></organisation>

=== opengreat-zhoukaihong/Hutchison/cbtb/mq_xml/op.xml
From:TL
To:CBTB
Content-Type:/text/XML-ORG
Date:2001.06.05 17:36:05
<?xml version="1.0"?>
<!DOCTYPE organisation SYSTEM "http://187.11.1.2:7001/organisation.dtd">


<organisation>
	
  <organisation_id>TL000064</organisation_id>
	
  <organisation_type>Shipper</organisation_type>
	
  <organisation_name>carmen 0509-test6</organisation_name>
	
	
  <organisation_address>
		
    <address1>organization.address1</address1>
		
    <address2>organization.address2</address2>
		
    <address3>organization.address3</address3>
		
	
  </organisation_address>
	
  <telephone>org-tel123</telephone>
	
  <mobile_no>cell-123</mobile_no>
	
  <fax_no>org-fax123</fax_no>
	
  <email>carmen.chan@line.net</email>
	
  <web_site>www.carmen.test.net</web_site>
	
	
  <contact_person>organization.contact</contact_person>
	
  <contact_person_chinese>contact-chinese</contact_person_chinese>
	
  <billing_sent_person>billing-contact</billing_sent_person>
	
  <billing_email>billing@contact.email</billing_email>
	
  <billing_address>
		
    <address1>billing-contact address1</address1>
		
    <address2>billing-contact address2</address2>
		
    <address3>billing-contact address3</address3>
		
    <address4>billing-contact address4</address4>
	
  </billing_address>
	
  <billing_fax_no>billing-contact-fax</billing_fax_no>
	
  <billing_telephone>billing-contact-phone</billing_telephone>
	
  <perfer_channel>EMAIL</perfer_channel>
	
  <perfer_language>en_US</perfer_language>
	
  <credit_amount>100</credit_amount>
	
  <payment_terms>COD</payment_terms>
	
  <reason_id>123</reason_id>
	
  <status>PENDING</status>
<registration_date>2001-05-16</registration_date>
	
  <remark>Remark of org_info_trucking</remark>
	
  <registration_reference_no>TL000064</registration_reference_no>
	
	
  <registration_channel>INTERNET</registration_channel>
	
  <document>
		
		
	</document>

</organisation>

=== opengreat-zhoukaihong/Hutchison/cbtb/mq_xml/sample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by peter (peter) -->
<!DOCTYPE organisation SYSTEM "http://187.11.1.125:7001/organisation.dtd">
<organisation>
	<organisation_id>TL000094</organisation_id>
	<organisation_type>Trucking Company</organisation_type>
	<organisation_name>Trucking Company ABC</organisation_name>
	<organisation_address>
		<address1>Rm1206, 12-F</address1>
		<address2>Fortress Tower</address2>
		<address3>North Point</address3>
		<address4>H.K.</address4>
	</organisation_address>
	<telephone>(852)12345678</telephone>
	<mobile_no>61001234</mobile_no>
	<fax_no>(852)12344556</fax_no>
	<email>abc@hotmail.com</email>
	<web_site>www.shipper.com</web_site>
	<business_registration_no>HK000017</business_registration_no>
	<contact_person>Chan Tai Man</contact_person>
	<billing_address>
		<address1>Rm1206, 12-F</address1>
		<address2>Fortress Tower</address2>
		<address3>North Point</address3>
	</billing_address>
	<perfer_channel>Phone</perfer_channel>
	<perfer_language>EN</perfer_language>
	<payment_terms>COD</payment_terms>
	<status>Registration in Progress</status>
	<registration_date>2001-05-16</registration_date>
	<registration_channel>internet</registration_channel>
	<UOM>KG, M</UOM>
	<document>
		<document_id>DOC01</document_id>
		<document_status>valid</document_status>
	</document>
</organisation>
